### ISSUE TITLE
pointcloud from interiornet dataset is skewed

### ISSUE THREAD

**Issue by ttsesm** [ethz-asl/interiornet_to_rosbag#1] opened 2020-08-24 09:06 UTC
Hi,

I was trying to use your code for processing the interiornet dataset and specifically the function for transforming the euclidean ray length to z coordinate https://github.com/ethz-asl/interiornet_to_rosbag/blob/1f43e446f8b58525eed9f91346b3d0da8ab54b5c/nodes/interiornet_to_rosbag.py#L58 but I've noticed that even after applying the transformation my pointcloud remains skewed as you can see below

![image](https://user-images.githubusercontent.com/10189018/91025476-b97fcf80-e5f9-11ea-9db4-5ad3f08139ed.png)
![image](https://user-images.githubusercontent.com/10189018/91025507-c69cbe80-e5f9-11ea-945c-a2a78aea4aaf.png)

any idea what could be the problem? Have you tested in your case that the created point clouds are fine?

In my case I am using the open3d library in the following principle:

```
import open3d as o3d
import numpy as np

def euclidean_ray_length_to_z_coordinate(depth_image, camera_model):
    center_x = camera_model.get_principal_point()[0]
    center_y = camera_model.get_principal_point()[1]

    constant_x = 1 / camera_model.get_focal_length()[0]
    constant_y = 1 / camera_model.get_focal_length()[1]

    vs = np.array([(v - center_x) * constant_x for v in range(0, depth_image.shape[1])])
    us = np.array([(u - center_y) * constant_y for u in range(0, depth_image.shape[0])])

    return (np.sqrt(np.square(depth_image / 1000.0) / (1 + np.square(vs[np.newaxis, :]) + np.square(us[:, np.newaxis]))) * 1000.0).astype(np.uint16)

if __name__ == '__main__':
    camera_intrinsics = o3d.camera.PinholeCameraIntrinsic()
    camera_intrinsics.set_intrinsics(640, 480, 600.0, 600.0, 320.0, 240.0)

    color = o3d.io.read_image('color.png')
    depthu = o3d.io.read_image('depth.png')
    depthf = o3d.geometry.Image(np.asarray(depthu).astype(np.float32))

    # process depthf using the euclidean_2_z function
    depthf_processed = o3d.geometry.Image(euclidiean_ray_lenght_to_z_coordinate(np.asarray(depthf), camera_intrinsics))

    # create rgbd image
    rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(color, depthf_processed, depth_trunc=4.0, convert_rgb_to_intensity=False)

    # create pointcloud from rgbd image
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, camera_intrinsics)

    # visualize point cloud
    o3d.visualization.draw_geometries([pcd])
```

Thanks.

**Comment by ftaubner** [comment] 2020-08-24 09:22
Hi,

Yes there was a mistake in the code. The euclidean depth image was published instead of the z depth image. The error should be fixed now.

**Comment by ttsesm** [comment] 2020-08-24 09:30
But the problem is that the returned `z_depth_image` from the https://github.com/ethz-asl/interiornet_to_rosbag/blob/68661d9a641134eaa285d08573d677f035b9f5d9/nodes/interiornet_to_rosbag.py#L58 function it seems not be correct.

**Comment by ttsesm** [comment] 2020-08-24 10:28
I've added a simple code snippet example in my initial message which you can test yourself

**Comment by ftaubner** [comment] 2020-08-24 10:57
I have tested your code and it seems to work fine. Maybe you can send me the image you are using? Is it from the InteriorNet dataset?

**Comment by ttsesm** [comment] 2020-08-24 11:52
Yes I am using the images from the Interiornet dataset. Here is a pair of images:
![rgb](https://user-images.githubusercontent.com/10189018/91041532-83017f00-e610-11ea-8f86-28215cbbb49f.png)
![depth](https://user-images.githubusercontent.com/10189018/91041537-8563d900-e610-11ea-8012-9cc9d6551b7d.png)
[open3d_reconstruction_system.zip](https://github.com/ethz-asl/interiornet_to_rosbag/files/5117541/open3d_reconstruction_system.zip)

And here you can see the output which is skewed:
![image](https://user-images.githubusercontent.com/10189018/91041864-0e7b1000-e611-11ea-8647-bc01c8383c37.png)

**Comment by ftaubner** [comment] 2020-08-24 12:17
The issue is with the open3d image loader. It may not load depth images correctly. Replace 
`depthu = o3d.io.read_image('depth.png')`
with
`depthu = cv2.imread('depth.png', cv2.IMREAD_UNCHANGED)`
and it should work.

**Comment by ttsesm** [comment] 2020-08-24 12:29
> The issue is with the open3d image loader. It may not load depth images correctly. Replace
> `depthu = o3d.io.read_image('depth.png')`
> with
> `depthu = cv2.imread('depth.png', cv2.IMREAD_UNCHANGED)`
> and it should work.

Interesting, indeed it works if I load the depth image with opencv. 
Thank you so much, I was fighting with this 3 days now and I never thought that the open3d loader might be the problem.

**Closed as completed** 2020-08-24 12:34 UTC

**Comment by ttsesm** [comment] 2020-08-24 15:05
@ftaubner one more question I am also trying to use the functions to get the correct pose, i.e.
```
def normalize(v):
    return v / np.linalg.norm(v)

def world_to_camera_with_pose(view_pose):
    camera_pose = view_pose[:3]
    lookat_pose = view_pose[3:6]
    up = view_pose[6:]
    R = np.diag(np.ones(4))
    R[2, :3] = normalize(lookat_pose - camera_pose)
    R[0, :3] = normalize(np.cross(R[2, :3], (up - camera_pose)))
    R[1, :3] = -normalize(np.cross(R[0, :3], R[2, :3]))
    T = np.diag(np.ones(4))
    T[:3, 3] = -camera_pose
    return R.dot(T)

def camera_to_world_with_pose(view_pose):
    return np.linalg.inv(world_to_camera_with_pose(view_pose))

# pose for the provided images
pose_init = np.array([39991664640, 0.0625990927, 0.580219448, 1.79874659, 0.185417295, 1.4658618, 1.35092223, 0.12411353, 1.02380025, 2.69286728])
view_pose = camera_to_world_with_pose(pose_init[1:])
pcd.transform(view_pose)
```

but then my output is shown from the top:
![image](https://user-images.githubusercontent.com/10189018/91060909-d1704700-e62b-11ea-9747-3ab20235cb37.png)
any idea what I might be doing wrong now?

**Comment by ttsesm** [comment] 2020-08-26 08:39
@ftaubner any idea how to resolve this?

**Comment by ttsesm** [comment] 2020-09-02 07:50
ok, problem solved by using the `world_to_camera_with_pose()` https://github.com/ethz-asl/interiornet_to_rosbag/blob/68661d9a641134eaa285d08573d677f035b9f5d9/nodes/interiornet_to_rosbag.py#L26 function. I had the view that this would transform the view perspective of the point cloud in the viewer when you pass it to the `open3d.transfrom()` but I was wrong.
